// src/lib/components/RadioPlayer.svelte
<script lang="ts">
  import Play from '@lucide/svelte/icons/play';
  import Pause from '@lucide/svelte/icons/pause';
  import ChevronUp from '@lucide/svelte/icons/chevron-up';
  import ChevronDown from '@lucide/svelte/icons/chevron-down';
  import RotateCcw from '@lucide/svelte/icons/rotate-ccw';
  import Radio from '@lucide/svelte/icons/radio';
  import { audioState, playRadio, pauseRadio, retryRadio, setRadioVolume, setExpanded } from '$lib/audio';
</script>

<aside class="lofi-player" class:expanded={$audioState.expanded} aria-label="Optional lofi radio">
  <div class="lofi-main-row">
    <button class="lofi-play" aria-label={$audioState.radioStatus === 'playing' ? 'Pause lofi radio' : 'Play lofi radio'} onclick={$audioState.radioStatus === 'playing' ? pauseRadio : playRadio}>
      {#if $audioState.radioStatus === 'playing'}<Pause />{:else}<Play />{/if}
    </button>
    <button class="lofi-summary" aria-label={$audioState.expanded ? 'Collapse radio controls' : 'Expand radio controls'} onclick={() => setExpanded(!$audioState.expanded)}>
      <span class:live={$audioState.radioStatus === 'playing'} class="lofi-signal"><Radio size={13} /></span>
      <span><b>Lofi companion</b><small aria-live="polite">{$audioState.radioStatus === 'idle' ? 'Off — no connection made' : $audioState.radioStatus}</small></span>
      {#if $audioState.expanded}<ChevronDown />{:else}<ChevronUp />{/if}
    </button>
  </div>
  {#if $audioState.expanded}
    <div class="lofi-details">
      <label><Radio /><input aria-label="Radio volume" type="range" min="0" max="1" step="0.01" value={$audioState.radioVolume} oninput={(event) => setRadioVolume(Number(event.currentTarget.value))} /><small>{Math.round($audioState.radioVolume * 100)}%</small></label>
      {#if $audioState.radioStatus === 'error'}<p>Stream unavailable. <button onclick={retryRadio}><RotateCcw size={12} /> Retry</button></p>{/if}
      <p>Pressing Play contacts <a href="https://loficafe.net/" target="_blank" rel="noreferrer">Lofi Cafe</a>, which receives ordinary network metadata. No check-in or private-model data is sent.</p>
    </div>
  {/if}
</aside>

// src/components/RadioPlayer.jsx
import { ChevronDown, ExternalLink, Pause, Play, Radio, RefreshCcw, Volume2, X } from 'lucide-react';
import { useAudio } from '../lib/audio.jsx';

export default function RadioPlayer({ hidden = false }) {
  const {
    radioStatus, radioVolume, setRadioVolume, playRadio, pauseRadio, retryRadio, expanded, setExpanded,
  } = useAudio();
  if (hidden) return null;
  const playing = radioStatus === 'playing';
  const connecting = radioStatus === 'connecting';

  return (
    <aside className={`lofi-player ${expanded ? 'expanded' : ''}`} aria-label="Unspool lofi radio">
      <div className="lofi-main-row">
        <button
          className="lofi-play"
          onClick={radioStatus === 'error' ? retryRadio : playing ? pauseRadio : playRadio}
          aria-label={radioStatus === 'error' ? 'Retry lofi radio' : playing ? 'Pause lofi radio' : 'Play lofi radio'}
          aria-describedby="lofi-provider-notice"
        >
          {radioStatus === 'error' ? <RefreshCcw /> : playing ? <Pause fill="currentColor" /> : <Play fill="currentColor" />}
        </button>
        <button className="lofi-summary" onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>
          <span className={`lofi-signal ${playing ? 'live' : ''}`}><Radio /></span>
          <span><b>quiet frequency</b><small>{connecting ? 'connecting…' : radioStatus === 'error' ? 'station unavailable' : playing ? 'chilling live' : 'Lofi Cafe · external'}</small></span>
          {expanded ? <X /> : <ChevronDown />}
        </button>
      </div>
      <div className="lofi-details" aria-hidden={!expanded}>
        <label>
          <Volume2 />
          <span className="sr-only">Radio volume</span>
          <input type="range" min="0" max="1" step="0.05" value={radioVolume} onChange={(event) => setRadioVolume(Number(event.target.value))} />
          <small>{Math.round(radioVolume * 100)}%</small>
        </label>
        <p>Optional ambience, not a health intervention. Pressing play contacts Lofi Cafe; no check-in data is shared.</p>
        <a href="https://loficafe.net/" target="_blank" rel="noreferrer">Stream by Lofi Cafe <ExternalLink /></a>
      </div>
      <span className="sr-only" aria-live="polite">Radio status: {radioStatus}</span>
      <span id="lofi-provider-notice" className="sr-only">Playing contacts the external Lofi Cafe stream. No Unspool check-in data is shared.</span>
    </aside>
  );
}
